# Generated by Django 4.1.7 on 2023-06-02 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fast_cars', '0004_remove_booking_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(null=True),
        ),
    ]
